apiVersion: v1
kind: Pod
metadata:
  name: cd
  namespace: go-demo-3-build
spec:
  containers:
  - name: docker
    image: docker:18.03-git
    command: ["sleep"]
    args: ["100000"]
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    - name: docker-socket
      mountPath: /var/run/docker.sock
    workingDir: /workspace
  - name: kubectl
    image: vfarcic/kubectl
    command: ["sleep"]
    args: ["100000"]
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    workingDir: /workspace
  - name: oc
    image: vfarcic/openshift-client
    command: ["sleep"]
    args: ["100000"]
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    workingDir: /workspace
  - name: golang
    image: golang:1.9
    command: ["sleep"]
    args: ["100000"]
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    workingDir: /workspace
  serviceAccount: build
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: Socket
  - name: workspace
    emptyDir: {}
